# Generated by Django 5.2.5 on 2025-08-28 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotes.source', verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(choices=[('movie', 'Фильм'), ('book', 'Книга'), ('series', 'Сериал'), ('game', 'Игра'), ('person', 'Люди'), ('other', 'Другое')], max_length=20, verbose_name='Тип'),
        ),
    ]
